window.FISH_FISHING_CONFIG = {
  versionPrefix: "1.1",
  gitCommitCount: 17,
  nestBuffSourceUrl:
    "https://raw.githubusercontent.com/luyh7/fishing-profit/gh-pages/nest-buff.json",
  baseIntervalHours: 1,
  statisticsHours: 24,
  rarityOrder: ["UR", "SSR", "SR", "R", "N"],
  rarityMultipliers: {
    UR: 16,
    SSR: 8,
    SR: 4,
    R: 2,
    N: 1,
  },
  hookLevels: [
    { level: 1, name: "鱼钩 Lv.1", speed: 0.1 },
    { level: 2, name: "鱼钩 Lv.2", speed: 0.2 },
    { level: 3, name: "鱼钩 Lv.3", speed: 0.3 },
    { level: 4, name: "鱼钩 Lv.4", speed: 0.4 },
    { level: 5, name: "鱼钩 Lv.5", speed: 0.5 },
    { level: 6, name: "鱼钩 Lv.6", speed: 0.6 },
    { level: 7, name: "鱼钩 Lv.7", speed: 0.7 },
    { level: 8, name: "鱼钩 Lv.8", speed: 0.8 },
    { level: 9, name: "鱼钩 Lv.9", speed: 0.9 },
    { level: 10, name: "鱼钩 Lv.10", speed: 1.0 },
  ],
  baitList: [
    { id: 1, name: "蚯蚓鱼饵", price: 2, speed: 0.2 },
    { id: 2, name: "虾米鱼饵", price: 5, speed: 0.4 },
    { id: 3, name: "拟饵", price: 10, speed: 0.6 },
    { id: 4, name: "黄金鱼饵", price: 18, speed: 0.8 },
    { id: 5, name: "魔法鱼饵", price: 30, speed: 1.0 },
    { id: 6, name: "传说鱼饵", price: 50, speed: 1.2 },
  ],
  systemBuffs: [
    { id: "none", name: "无", value: 0 },
    { id: "weekend", name: "周末加速 30%", value: 30 },
  ],
  maps: [
    {
      id: 1,
      difficulty: 0,
      name: "乡间浅溪",
      fishes: [
        { name: "小鲫鱼", nPrice: 9 },
        { name: "麦穗鱼", nPrice: 11 },
        { name: "白条鱼", nPrice: 10 },
        { name: "鳑鲏鱼", nPrice: 9 },
        { name: "泥鳅", nPrice: 11 },
      ],
    },
    {
      id: 2,
      difficulty: 1,
      name: "田园池塘",
      fishes: [
        { name: "草鱼", nPrice: 12 },
        { name: "鲤鱼", nPrice: 14 },
        { name: "鲢鱼", nPrice: 13 },
        { name: "鳙鱼", nPrice: 12 },
        { name: "黄鳝", nPrice: 14 },
      ],
    },
    {
      id: 3,
      difficulty: 2,
      name: "平缓内河",
      fishes: [
        { name: "翘嘴鲌", nPrice: 15 },
        { name: "鲶鱼", nPrice: 19 },
        { name: "土凤鱼", nPrice: 17 },
        { name: "黑鱼", nPrice: 16 },
        { name: "黄颡鱼", nPrice: 18 },
      ],
    },
    {
      id: 4,
      difficulty: 3,
      name: "宽阔大湖",
      fishes: [
        { name: "青鱼", nPrice: 21 },
        { name: "鳊鱼", nPrice: 25 },
        { name: "赤眼鳟", nPrice: 23 },
        { name: "银鱼", nPrice: 22 },
        { name: "花鲢", nPrice: 24 },
      ],
    },
    {
      id: 5,
      difficulty: 4,
      name: "山泉深潭",
      fishes: [
        { name: "马口鱼", nPrice: 27 },
        { name: "石斑鱼", nPrice: 33 },
        { name: "光唇鱼", nPrice: 30 },
        { name: "宽鳍鱲", nPrice: 28 },
        { name: "小银鲫", nPrice: 32 },
      ],
    },
    {
      id: 6,
      difficulty: 5,
      name: "芦苇浅荡",
      fishes: [
        { name: "革胡子鲶", nPrice: 35 },
        { name: "麦鲮鱼", nPrice: 43 },
        { name: "泰鲮鱼", nPrice: 39 },
        { name: "罗非鱼", nPrice: 37 },
        { name: "食蚊鱼", nPrice: 41 },
      ],
    },
    {
      id: 7,
      difficulty: 6,
      name: "长江中游",
      fishes: [
        { name: "江团鱼", nPrice: 0 },
        { name: "刀鲚", nPrice: 0 },
        { name: "黄尾鲴", nPrice: 0 },
        { name: "细鳞鱼", nPrice: 0 },
        { name: "重唇鱼", nPrice: 0 },
      ],
    },
    {
      id: 8,
      difficulty: 7,
      name: "河口交汇",
      fishes: [
        { name: "海鲈", nPrice: 0 },
        { name: "鲻鱼", nPrice: 0 },
        { name: "梭鱼", nPrice: 0 },
        { name: "弹涂鱼", nPrice: 0 },
        { name: "小海鳗", nPrice: 0 },
      ],
    },
    {
      id: 9,
      difficulty: 8,
      name: "高山冷湖",
      fishes: [
        { name: "虹鳟鱼", nPrice: 0 },
        { name: "金鳟鱼", nPrice: 0 },
        { name: "柳根鱼", nPrice: 0 },
        { name: "高原鳅", nPrice: 0 },
        { name: "细鳞鲑", nPrice: 0 },
      ],
    },
    {
      id: 10,
      difficulty: 9,
      name: "原生古河",
      fishes: [
        { name: "胭脂鱼", nPrice: 0 },
        { name: "斑鳜", nPrice: 0 },
        { name: "大眼鳜", nPrice: 0 },
        { name: "长吻鮠", nPrice: 0 },
        { name: "乌苏里拟鲿", nPrice: 0 },
      ],
    },
  ],
  rodLevels: [
    { level: 0, name: "鱼竿 Lv.0" },
    { level: 1, name: "鱼竿 Lv.1" },
    { level: 2, name: "鱼竿 Lv.2" },
    { level: 3, name: "鱼竿 Lv.3" },
    { level: 4, name: "鱼竿 Lv.4" },
    { level: 5, name: "鱼竿 Lv.5" },
    // { level: 6, name: "鱼竿 Lv.6" },
    // { level: 7, name: "鱼竿 Lv.7" },
    // { level: 8, name: "鱼竿 Lv.8" },
    // { level: 9, name: "鱼竿 Lv.9" },
    // { level: 10, name: "鱼竿 Lv.10" },
  ],
  probabilityByDelta: {
    0: { UR: 0, SSR: 0, SR: 0, R: 33.45, N: 66.55 },
    1: { UR: 0, SSR: 0, SR: 7.9, R: 42.46, N: 49.64 },
    2: { UR: 0, SSR: 0, SR: 18.08, R: 50.39, N: 31.53 },
    3: { UR: 0, SSR: 0, SR: 34.72, R: 48.9, N: 16.38 },
    4: { UR: 0, SSR: 11.37, SR: 44.12, R: 37.74, N: 6.77 },
    5: { UR: 0, SSR: 25.64, SR: 51.01, R: 23.35, N: 0 },
    6: { UR: 7, SSR: 9, SR: 16, R: 26, N: 42 },
    7: { UR: 9, SSR: 11, SR: 18, R: 27, N: 35 },
    8: { UR: 11, SSR: 13, SR: 20, R: 28, N: 28 },
    9: { UR: 13, SSR: 15, SR: 22, R: 26, N: 24 },
    10: { UR: 15, SSR: 18, SR: 24, R: 23, N: 20 },
  },
};
