window.FISH_FISHING_CONFIG = {
  versionPrefix: "1.1",
  gitCommitCount: 103,
  nestBuffSourceUrl:
    "https://fishing-profit-nest-buff.470103427.workers.dev/nest-buff.json",
  baseIntervalHours: 1,
  statisticsHours: 24,
  rarityOrder: ["UTR", "UR", "SSR", "SR", "R", "N"],
  rarityMultipliers: {
    UTR: 32,
    UR: 16,
    SSR: 8,
    SR: 4,
    R: 2,
    N: 1,
  },
  displayFrameDropRatePercent: 0.7,
  displayFramePityCount: 150,
  displayFrameValue: 0,
  specialUtrPityCount: 150,
  catFramePityCount: 15,
  catFrameValue: 200,
  hookLevels: [
    { level: 0, name: "鱼钩 Lv.0", speed: 0 },
    { level: 1, name: "鱼钩 Lv.1", speed: 0.1 },
    { level: 2, name: "鱼钩 Lv.2", speed: 0.2 },
    { level: 3, name: "鱼钩 Lv.3", speed: 0.3 },
    { level: 4, name: "鱼钩 Lv.4", speed: 0.4 },
    { level: 5, name: "鱼钩 Lv.5", speed: 0.5 },
    { level: 6, name: "鱼钩 Lv.6", speed: 0.6 },
    { level: 7, name: "鱼钩 Lv.7", speed: 0.7 },
    { level: 8, name: "鱼钩 Lv.8", speed: 0.8 },
    { level: 9, name: "鱼钩 Lv.9", speed: 0.9 },
    { level: 10, name: "鱼钩 Lv.10", speed: 1.0 },
  ],
  baitList: [
    { id: 1, name: "蚯蚓鱼饵", price: 2, speed: 0.2 },
    { id: 2, name: "虾米鱼饵", price: 5, speed: 0.4 },
    { id: 3, name: "拟饵", price: 10, speed: 0.6 },
    { id: 4, name: "黄金鱼饵", price: 18, speed: 0.8 },
    { id: 5, name: "魔法鱼饵", price: 30, speed: 1.0 },
    { id: 6, name: "传说鱼饵", price: 50, speed: 1.2 },
  ],
  systemBuffs: [
    { id: "none", name: "无", value: 0 },
    { id: "weekend", name: "加速30%", value: 30 },
  ],
  potions: [
    {
      id: "none",
      name: "无",
      rodLevelPenalty: 0,
      fishCatchMultiplier: 1,
    },
    {
      id: "duoduo",
      name: "多多药水",
      effectText: "鱼竿等级-1，鱼获数量翻倍",
      rodLevelPenalty: 1,
      fishCatchMultiplier: 2,
    },
    {
      id: "lucky_double",
      name: "幸运药水",
      effectText: "每次鱼获判定2次，取更好的结果",
      rodLevelPenalty: 0,
      fishCatchMultiplier: 1,
      bestCatchRolls: 2,
    },
  ],
  catParadise: {
    mapId: "S1",
    collectionIndex: 20,
    maxOpenLevel: 3,
    buildings: [
      {
        id: "catCabin",
        order: 1,
        name: "猫猫小木屋",
        levels: [
          {
            level: 1,
            effects: { baitSavingPercent: 3 },
          },
          {
            level: 2,
            effects: { baitSavingPercent: 3 },
          },
          {
            level: 3,
            effects: { baitSavingPercent: 4 },
          },
        ],
      },
      {
        id: "catFishPond",
        order: 2,
        name: "喵喵鱼塘",
        levels: [
          {
            level: 1,
            effects: { fishingSpeedPercent: 3 },
          },
          {
            level: 2,
            effects: { fishingSpeedPercent: 3 },
          },
          {
            level: 3,
            effects: { fishingSpeedPercent: 4 },
          },
        ],
      },
      {
        id: "catClimbingPlaza",
        order: 3,
        name: "猫爬架广场",
        baseEffects: { materialDropRatePercent: 30 },
        levels: [
          {
            level: 1,
            effects: { materialDropRatePercent: 5 },
          },
          {
            level: 2,
            effects: { materialDropRatePercent: 5 },
          },
          {
            level: 3,
            effects: { materialDropRatePercent: 5 },
          },
        ],
      },
      {
        id: "catCafe",
        order: 4,
        name: "喵咖咖啡馆",
        levels: [
          {
            level: 1,
            effects: { fishPricePercent: 3 },
          },
          {
            level: 2,
            effects: { fishPricePercent: 3 },
          },
          {
            level: 3,
            effects: { fishPricePercent: 4 },
          },
        ],
      },
      {
        id: "catCoaster",
        order: 5,
        name: "猫猫过山车",
        levels: [
          {
            level: 1,
            effects: { weatherBoostPercent: 3 },
          },
          {
            level: 2,
            effects: { weatherBoostPercent: 3 },
          },
          {
            level: 3,
            effects: { weatherBoostPercent: 4 },
          },
        ],
      },
      {
        id: "spinningCatTeaser",
        order: 6,
        name: "旋转逗猫棒",
        levels: [
          {
            level: 1,
            effects: { doubleCatchPercent: 3 },
          },
          {
            level: 2,
            effects: { doubleCatchPercent: 3 },
          },
          {
            level: 3,
            effects: { doubleCatchPercent: 4 },
          },
        ],
      },
      {
        id: "crystalCatCastle",
        order: 7,
        name: "水晶猫城堡",
        levels: [
          {
            level: 1,
            effects: { rodLevelBonusChancePercent: 5 },
          },
          {
            level: 2,
            effects: { rodLevelBonusChancePercent: 10 },
          },
          {
            level: 3,
            effects: { rodLevelBonusChancePercent: 15 },
          },
        ],
      },
      {
        id: "catFerrisWheel",
        order: 8,
        name: "猫咪摩天轮",
        levels: [
          {
            level: 1,
            effects: { dailySignDraws: 1 },
          },
          {
            level: 2,
            effects: { dailySignDraws: 1 },
          },
          {
            level: 3,
            effects: { dailySignDraws: 1 },
          },
        ],
      },
      {
        id: "legendaryCatStatue",
        order: 9,
        name: "传奇猫雕像",
        levels: [
          {
            level: 1,
            effects: { unlockLevel: 2 },
          },
          {
            level: 2,
            effects: { unlockLevel: 1 },
          },
          {
            level: 3,
            effects: { rodLevelBonus: 1, materialValue: 80 },
          },
        ],
      },
    ],
  },
  maps: [
    {
      id: 1,
      difficulty: 0,
      name: "乡间浅溪",
      fishes: [
        { name: "小鲫鱼", nPrice: 9 },
        { name: "麦穗鱼", nPrice: 11 },
        { name: "白条鱼", nPrice: 10 },
        { name: "鳑鲏鱼", nPrice: 9 },
        { name: "泥鳅", nPrice: 11 },
      ],
    },
    {
      id: 2,
      difficulty: 1,
      name: "田园池塘",
      fishes: [
        { name: "草鱼", nPrice: 12 },
        { name: "鲤鱼", nPrice: 14 },
        { name: "鲢鱼", nPrice: 13 },
        { name: "鳙鱼", nPrice: 12 },
        { name: "黄鳝", nPrice: 14 },
      ],
    },
    {
      id: 3,
      difficulty: 2,
      name: "平缓内河",
      fishes: [
        { name: "翘嘴鲌", nPrice: 15 },
        { name: "鲶鱼", nPrice: 19 },
        { name: "土凤鱼", nPrice: 17 },
        { name: "黑鱼", nPrice: 16 },
        { name: "黄颡鱼", nPrice: 18 },
      ],
    },
    {
      id: 4,
      difficulty: 3,
      name: "宽阔大湖",
      fishes: [
        { name: "青鱼", nPrice: 21 },
        { name: "鳊鱼", nPrice: 25 },
        { name: "赤眼鳟", nPrice: 23 },
        { name: "银鱼", nPrice: 22 },
        { name: "花鲢", nPrice: 24 },
      ],
    },
    {
      id: 5,
      difficulty: 4,
      name: "山泉深潭",
      fishes: [
        { name: "马口鱼", nPrice: 27 },
        { name: "石斑鱼", nPrice: 33 },
        { name: "光唇鱼", nPrice: 30 },
        { name: "宽鳍鱲", nPrice: 28 },
        { name: "小银鲫", nPrice: 32 },
      ],
    },
    {
      id: 6,
      difficulty: 5,
      name: "芦苇浅荡",
      fishes: [
        { name: "革胡子鲶", nPrice: 35 },
        { name: "麦鲮鱼", nPrice: 43 },
        { name: "泰鲮鱼", nPrice: 39 },
        { name: "罗非鱼", nPrice: 37 },
        { name: "食蚊鱼", nPrice: 41 },
      ],
    },
    {
      id: 7,
      difficulty: 6,
      name: "长江中游",
      fishes: [
        { name: "江团鱼", nPrice: 47 },
        { name: "刀鲚", nPrice: 57 },
        { name: "黄尾鲴", nPrice: 52 },
        { name: "细鳞鱼", nPrice: 49 },
        { name: "重唇鱼", nPrice: 55 },
      ],
    },
    {
      id: 8,
      difficulty: 7,
      name: "河口交汇",
      fishes: [
        { name: "海鲈", nPrice: 61 },
        { name: "鲻鱼", nPrice: 75 },
        { name: "梭鱼", nPrice: 68 },
        { name: "弹涂鱼", nPrice: 64 },
        { name: "小海鳗", nPrice: 72 },
      ],
    },
    {
      id: 9,
      difficulty: 8,
      name: "高山冷湖",
      fishes: [
        { name: "虹鳟鱼", nPrice: 80 },
        { name: "金鳟鱼", nPrice: 98 },
        { name: "柳根鱼", nPrice: 89 },
        { name: "高原鳅", nPrice: 84 },
        { name: "细鳞鲑", nPrice: 94 },
      ],
    },
    {
      id: 10,
      difficulty: 9,
      name: "原生古河",
      fishes: [
        { name: "胭脂鱼", nPrice: 106 },
        { name: "斑鳜", nPrice: 130 },
        { name: "大眼鳜", nPrice: 118 },
        { name: "长吻鮠", nPrice: 112 },
        { name: "乌苏里拟鲿", nPrice: 124 },
      ],
    },
    {
      id: 11,
      difficulty: 10,
      name: "牛奶河",
      fishes: [
        { name: "月乳鲫", nPrice: 169 },
        { name: "银匙鳐", nPrice: 183 },
        { name: "星沫鳗", nPrice: 175 },
        { name: "奶冠鲤", nPrice: 172 },
        { name: "银河灯鱼", nPrice: 179 },
      ],
    },
    {
      id: 12,
      difficulty: 11,
      name: "月环港",
      fishes: [
        { name: "月壳蟹鱼", nPrice: 194 },
        { name: "潮汐银鲈", nPrice: 210 },
        { name: "环月飞鱼", nPrice: 200 },
        { name: "玉兔灯鲷", nPrice: 198 },
        { name: "灰晶鳕", nPrice: 206 },
      ],
    },
    {
      id: 13,
      difficulty: 12,
      name: "彗尾瀑",
      fishes: [
        { name: "彗尾鲑", nPrice: 221 },
        { name: "焰尘鳟", nPrice: 239 },
        { name: "长尾星鳅", nPrice: 230 },
        { name: "白火鲢", nPrice: 226 },
        { name: "碎冰虹鱼", nPrice: 235 },
      ],
    },
    {
      id: 14,
      difficulty: 13,
      name: "星砂漠",
      fishes: [
        { name: "沙星魟", nPrice: 253 },
        { name: "琉璃沙鳗", nPrice: 275 },
        { name: "星蝎鲶", nPrice: 264 },
        { name: "金尘鲷", nPrice: 259 },
        { name: "海市蜃鱼", nPrice: 269 },
      ],
    },
    {
      id: 15,
      difficulty: 14,
      name: "云鲸庭",
      fishes: [
        { name: "云须鲸鱼", nPrice: 290 },
        { name: "鲸歌鲤", nPrice: 314 },
        { name: "浮庭鲫", nPrice: 301 },
        { name: "天羽鳐", nPrice: 296 },
        { name: "雾铃鳕", nPrice: 308 },
      ],
    },
    {
      id: 16,
      difficulty: 15,
      name: "极光井",
      fishes: [
        { name: "极光鳗", nPrice: 332 },
        { name: "虹幕鲑", nPrice: 360 },
        { name: "井心灯鱼", nPrice: 346 },
        { name: "绿辉鲈", nPrice: 339 },
        { name: "磁光鳟", nPrice: 353 },
      ],
    },
    {
      id: 17,
      difficulty: 16,
      name: "黑洞涡",
      fishes: [
        { name: "引力鲶", nPrice: 381 },
        { name: "暗环魟", nPrice: 412 },
        { name: "奇点鳕", nPrice: 396 },
        { name: "坠星鳗", nPrice: 389 },
        { name: "潮汐黑鲤", nPrice: 405 },
      ],
    },
    {
      id: 18,
      difficulty: 17,
      name: "水晶星冠",
      fishes: [
        { name: "晶冠鲷", nPrice: 435 },
        { name: "棱镜鲫", nPrice: 472 },
        { name: "星核金鱼", nPrice: 453 },
        { name: "蓝晶鳟", nPrice: 445 },
        { name: "冠冕灯鲈", nPrice: 463 },
      ],
    },
    {
      id: 19,
      difficulty: 18,
      name: "时钟星湖",
      fishes: [
        { name: "秒针鲑", nPrice: 498 },
        { name: "回环鳗", nPrice: 540 },
        { name: "逆刻鲤", nPrice: 519 },
        { name: "钟摆鲈", nPrice: 509 },
        { name: "永昼银鱼", nPrice: 529 },
      ],
    },
    {
      id: 20,
      difficulty: 19,
      name: "奇迹彼岸",
      fishes: [
        { name: "奇迹锦鲤", nPrice: 570 },
        { name: "终星鳐", nPrice: 618 },
        { name: "愿核灯鱼", nPrice: 594 },
        { name: "彼岸银鲑", nPrice: 582 },
        { name: "九曜梦鱼", nPrice: 606 },
      ],
    },
    {
      id: "S1",
      difficulty: 6,
      name: "猫猫乐园",
      maxRarity: "UR",
      fishes: [
        { name: "橘座鲫鱼", nPrice: 47 },
        { name: "暹罗鳊鱼", nPrice: 57 },
        { name: "布偶白条", nPrice: 52 },
        { name: "奶牛麦穗", nPrice: 49 },
        { name: "三花泥鳅", nPrice: 55 },
        { name: "金渐层锦鲤", nPrice: 48 },
        { name: "英短青鱼", nPrice: 56 },
        { name: "无毛鲶鱼", nPrice: 52 },
        { name: "折耳翘嘴", nPrice: 50 },
        { name: "卷耳黄颡", nPrice: 54 },
      ],
    },
  ],
  rodLevels: [
    { level: 0, name: "鱼竿 Lv.0" },
    { level: 1, name: "鱼竿 Lv.1" },
    { level: 2, name: "鱼竿 Lv.2" },
    { level: 3, name: "鱼竿 Lv.3" },
    { level: 4, name: "鱼竿 Lv.4" },
    { level: 5, name: "鱼竿 Lv.5" },
    { level: 6, name: "鱼竿 Lv.6" },
    { level: 7, name: "鱼竿 Lv.7" },
    { level: 8, name: "鱼竿 Lv.8" },
    { level: 9, name: "鱼竿 Lv.9" },
    { level: 10, name: "鱼竿 Lv.10" },
    { level: 11, name: "鱼竿 Lv.11" },
    { level: 12, name: "鱼竿 Lv.12" },
    { level: 13, name: "鱼竿 Lv.13" },
    { level: 14, name: "鱼竿 Lv.14" },
    { level: 15, name: "鱼竿 Lv.15" },
    { level: 16, name: "鱼竿 Lv.16" },
    { level: 17, name: "鱼竿 Lv.17" },
    { level: 18, name: "鱼竿 Lv.18" },
    { level: 19, name: "鱼竿 Lv.19" },
    { level: 20, name: "鱼竿 Lv.20" },
    { level: 21, name: "鱼竿 Lv.21" },
  ],
  rarityDistribution: [
    [0.6655, 0.3345, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    [0.4964, 0.4246, 0.079, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    [0.3153, 0.5039, 0.1808, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    [0.1638, 0.489, 0.3472, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    [0.0677, 0.3774, 0.4412, 0.1137, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    [0, 0.2335, 0.5101, 0.2564, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    [0, 0.0291, 0.5209, 0.4, 0.05, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    [0, 0, 0.1937, 0.6863, 0.12, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    [0, 0, 0.1638, 0.489, 0.3472, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    [0, 0, 0.0677, 0.3774, 0.4412, 0.1137, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    [0, 0, 0, 0.2335, 0.5101, 0.2564, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    [0, 0, 0, 0.1085, 0.4426, 0.3785, 0.0704, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0.3153, 0.5039, 0.1808, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0.1638, 0.489, 0.3472, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0.0677, 0.3774, 0.4412, 0.1137, 0, 0, 0, 0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0, 0.2335, 0.5101, 0.2564, 0, 0, 0, 0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0, 0.1085, 0.4426, 0.3785, 0.0704, 0, 0, 0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0, 0, 0.3153, 0.5039, 0.1808, 0, 0, 0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0, 0, 0.1638, 0.489, 0.3472, 0, 0, 0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0, 0, 0.0677, 0.3774, 0.4412, 0.1137, 0, 0, 0, 0, 0, 0],
  ],
};
